// src/components/Home/Footer.jsx
import { FaInstagram, FaTwitter, FaFacebook } from "react-icons/fa";

const Footer = () => {
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <footer className="bg-custom-blue font-sans py-5 px-4 sm:px-6 md:px-10 lg:px-24">
      <div className="flex flex-col md:flex-row items-center justify-between text-center md:text-left">
        <div className="logo mb-4 md:mb-0">
          <img src="logo/image.webp" alt="logo" className="h-16 md:h-20" />
        </div>
        <div>
          <h1 className="text-white text-xl sm:text-2xl md:text-3xl font-bold">
            Jaruratcare <span className="text-[#D8E74E]">Foundation</span>
          </h1>
          <p className="text-white text-sm md:text-base">
            Jaisi Jarurat, Vaisi Care
          </p>
        </div>
        <div className="flex flex-col sm:flex-row space-y-3 sm:space-y-0 sm:space-x-4 mt-4 md:mt-0">
          <button className="bg-[#D8E74E] text-black font-bold py-2 px-3 sm:px-4 md:px-5 rounded-full cursor-pointer">
            Seek Support
          </button>
          <button className="bg-[#2C72B9] text-white font-bold py-2 px-3 sm:px-4 md:px-5 rounded-full cursor-pointer">
            Donate
          </button>
        </div>
      </div>

      <hr className="my-5 border-gray-300" />

      <div className="flex flex-col md:flex-row text-white text-sm justify-between py-5 gap-5 text-center md:text-left">
        <div className="flex flex-col space-y-2">
          <p>Home</p>
          <p>Mission</p>
          <p>Volunteer</p>
          <p>Locate Hospitals</p>
          <p>Terms & Conditions</p>
        </div>
        <div className="flex flex-col space-y-2">
          <p>About Us</p>
          <p>Blogs</p>
          <p>News</p>
          <p>Contact Us</p>
        </div>
        <div className="flex flex-col space-y-2">
          <p>Connect with us</p>
          <div className="flex justify-center md:justify-start space-x-4">
            <FaInstagram className="h-6 cursor-pointer" />
            <FaTwitter className="h-6 cursor-pointer" />
            <FaFacebook className="h-6 cursor-pointer" />
          </div>
        </div>
      </div>

      <hr className="my-5 border-gray-300" />

      <div className="flex flex-col md:flex-row text-[#204D80] justify-between py-5 text-center md:text-left">
        <div className="flex flex-col sm:flex-row space-x-2 cursor-pointer mb-2 md:mb-0">
          <p>Privacy policy</p>
          <p>Terms of service</p>
        </div>
        <div>
          <p>&copy;2024 HANDSCART LCC. All rights reserved</p>
        </div>
        <div className="text-[#D8E74E] cursor-pointer" onClick={scrollToTop}>
          <p>Back to Top &uarr;</p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// src/lib/components/Footer/footer.svelte
<script>
    import  Icon from '@iconify/svelte';
  </script>
  
    
    <footer class="bg-[#132442] font-sans py-5">
      <div class="flex items-center justify-between mx-24">
        <div class="logo">
          <img src="./images/logo.svg" alt="logo" height="85px" />
        </div>
        <div>
          <h1 class="text-white text-3xl font-bold">
            Jaruratcare <span class="text-[#D8E74E]">Foundation</span>
          </h1>
          <p class="text-white text-base">Jaisi Jarurat, Vaisi Care</p>
        </div>
        <div class="flex space-x-8">
          <button class="bg-[#D8E74E] text-black font-bold py-2 px-5 rounded-full border-none cursor-pointer">Seek Support</button>
          <button class="bg-[#2C72B9] text-white font-bold py-2 px-5 rounded-full border-none cursor-pointer">Donate</button>
        </div>
      </div>
    
      <hr class="my-5 mx-24 border-gray-300" />
    
      <div class="flex text-white text-sm justify-end py-5 mx-24 gap-5">
        <div class="flex flex-col space-y-2">
          <p>Home</p>
          <p>Mission</p>
          <p>Volunteer</p>
          <p>Locate Hospitals</p>
          <p>Terms & Conditions</p>
        </div>
        <div class="flex flex-col space-y-2">
          <p>About Us</p>
          <p>Blogs</p>
          <p>News</p>
          <p>Contact Us</p>
        </div>
        <div class="flex flex-col space-y-2">
          <p>Connect with us</p>
          <div class="flex space-x-5">
            <Icon icon="mdi:instagram" class="icon h-7 cursor-pointer" />
            <Icon icon="mdi:twitter" class="icon h-7 cursor-pointer" />
            <Icon icon="mdi:facebook" class="icon h-7 cursor-pointer" />
          </div>
        </div>
      </div>
    
      <hr class="my-5 mx-24 border-gray-300" />
    
      <div class="flex text-[#204D80] justify-between mx-24 py-5">
        <div class="flex space-x-2 cursor-pointer">
          <p>Privacy policy</p>
          <p>Terms of service</p>
        </div>
        <div>
          <p>&copy;2024 HANDSCART LCC. All right reserved</p>
        </div>
        <div class="text-[#D8E74E] cursor-pointer">
          <p>Back to Top &uarr;</p>
        </div>
      </div>
    </footer>
