// src/lib/components/donation.svelte
<script>
  import Donate from '../../assets/svg/donate.svelte';
  import Member from '../../assets/svg/member.svelte';
  import SeekSupport from '../../assets/svg/seekSupport.svelte';
  import DonationBg from '../../assets/svg/donationBg.svelte';
</script>

<div class=" relative w-full flex justify-between border border-[#0072C4]" >
  <div class="absolute w-full h-full z-0 overflow-hidden">
    <DonationBg />
  </div>

  <div class="w-1/3 py-12 px-32 flex flex-col justify-center items-center  z-10">
    <span class="bg-white p-3 rounded-full"><SeekSupport /></span>
    <h2
      class="mt-6 mb-12 text-4xl font-bold font-serif text-center"
      style="font-family: 'Playfair Display', sans-serif;"
    >
      Seek Support
    </h2>
    <p class="mt-2 text-center text-sm">
      Our NGO is here to help you through your cancer journey. <span class="font-bold"
        >Reach out to us today.</span
      >
    </p>
    <button
      class="relative z-1 mt-8 px-8 py-3 bg-[#0155BD] text-xl text-white border-2 border-[#0155BD] rounded-full hover:text-blue-950 group flex items-center justify-center overflow-hidden duration-200 ease"
      style="font-family: 'Roboto', sans-serif;"
    >
      <span
        class="absolute bottom-0 left-1/2 right-1/2 w-0 h-0 bg-[#DBEAFE] rounded-full transition-all duration-400 ease group-hover:w-full group-hover:h-full group-hover:left-0 group-hover:bottom-0 group-hover:right-0"
        style="transform: translateX(-50%), translateX(50%);"
      ></span>
      <span class="relative">Seek Support</span>
    </button>
  </div>

  <div class="w-1/3 py-12 px-32 flex flex-col justify-center items-center border-x border-[#0072C4] z-10">
    <span class="bg-white p-3 rounded-full"><Donate /></span>
    <h2
      class="mt-6 mb-12 text-4xl font-bold font-serif text-center"
      style="font-family: 'Playfair Display', sans-serif;"
    >
      Donate
    </h2>
    <p class="mt-2 text-center text-sm">
      One Life at a Time "<span class="font-bold">Donate</span> today and be the light that brings hope
      and healing to cancer patients."
    </p>
    <button
      class="relative z-1 mt-8 px-8 py-3 bg-[#0155BD] text-xl text-white border-2 border-[#0155BD] rounded-full hover:text-blue-950 group flex items-center justify-center overflow-hidden duration-200 ease"
      style="font-family: 'Roboto', sans-serif;"
    >
      <span
        class="absolute bottom-0 left-1/2 right-1/2 w-0 h-0 bg-[#DBEAFE] rounded-full transition-all duration-400 ease group-hover:w-full group-hover:h-full group-hover:left-0 group-hover:bottom-0 group-hover:right-0"
        style="transform: translateX(-50%), translateX(50%);"
      ></span>
      <span class="relative">Donate Now</span>
    </button>
  </div>

  <div class="w-1/3 py-12 px-32 flex flex-col justify-center items-center  z-10">
    <span class="bg-white p-3 rounded-full"><Member /></span>
    <h2
      class="mt-6 mb-12 text-4xl font-bold font-serif text-center"
      style="font-family: 'Playfair Display', sans-serif;"
    >
      Become a Member
    </h2>
    <p class="mt-2 text-center text-sm">
      Be a hero. <span class="font-bold">Volunteer</span> with us and provide support and hope to those
      affected by cancer.
    </p>
    <button
      class="relative z-1 mt-8 px-8 py-3 bg-[#0155BD] text-xl text-white border-2 border-[#0155BD] rounded-full hover:text-blue-950 group flex items-center justify-center overflow-hidden duration-200 ease"
      style="font-family: 'Roboto', sans-serif;"
    >
      <span
        class="absolute bottom-0 left-1/2 right-1/2 w-0 h-0 bg-[#DBEAFE] rounded-full transition-all duration-400 ease group-hover:w-full group-hover:h-full group-hover:left-0 group-hover:bottom-0 group-hover:right-0"
        style="transform: translateX(-50%), translateX(50%);"
      ></span>
      <span class="relative">Get Started</span>
    </button>
  </div>
</div>

// src/components/Home/Donation.jsx
import HeartDonateIcon from "../../assets/svg/HeartDonateIcon.jsx";
import DonateBg from "../../assets/svg/Donatebg.jsx";
import SeekSupportIcon from "../../assets/svg/SeekSupportIcon.jsx";
import MemberIcon from "../../assets/svg/MemberIcon.jsx";
import Button from "./Button.jsx";

const SupportDonateMember = () => {
  return (
    <div className="relative w-full border border-[#0072C4] bg-white overflow-hidden mb-10">
      {/* Background */}
      <div className="absolute w-full h-full z-0 inset-0 overflow-hidden">
        <DonateBg />
      </div>

      {/* Content Grid */}
      <div className="relative z-10 grid grid-cols-1 md:grid-cols-3 text-center text-white">
        {/* Seek Support */}
        <div className="py-8 px-6 flex flex-col justify-center items-center border-b md:border-b-0">
          <span className="bg-white p-3 rounded-full">
            <SeekSupportIcon />
          </span>
          <h2 className="md:mt-6 md:mb-6 mt-4 mb-4 text-2xl md:text-4xl font-bold font-serif text-[#0155BD]">
            Seek Support
          </h2>
          <p className="text-gray-800 text-sm md:text-base w-[70%] md:w-[50%] mt-8 md:mt-12">
            Our NGO is here to help you through your cancer journey.{" "}
            <span className="font-bold">Reach out to us today.</span>
          </p>
          <Button text="Seek Support" />
        </div>

        {/* Donate */}
        <div className="py-8 px-6 flex flex-col justify-center items-center border-t md:border-t-0 md:border-x border-[#0072C4] border-b">
          <span className="bg-white p-3 rounded-full">
            <HeartDonateIcon />
          </span>
          <h2 className="md:mt-6 md:mb-6 mt-4 mb-4 text-2xl md:text-4xl font-bold font-serif text-[#0155BD]">
            Donate
          </h2>
          <p className="text-gray-800 text-sm md:text-base w-[70%] md:w-[50%] mt-8 md:mt-12">
            One Life at a Time. <span className="font-bold">Donate</span> today
            and be the light that brings hope and healing to cancer patients.
          </p>
          <Button text="Donate Now" />
        </div>

        {/* Become a Member */}
        <div className="py-8 px-6 flex flex-col justify-center items-center">
          <span className="bg-white p-3 rounded-full">
            <MemberIcon />
          </span>
          <h2 className="md:mt-6 md:mb-6 mt-4 mb-4 text-2xl md:text-4xl font-bold font-serif text-[#0155BD]">
            Become a Member
          </h2>
          <p className="text-gray-800 text-sm md:text-base w-[70%] md:w-[50%] mt-8 md:mt-12">
            Be a hero. <span className="font-bold">Volunteer</span> with us and
            provide support and hope to those affected by cancer.
          </p>
          <Button text="Get Started" />
        </div>
      </div>
    </div>
  );
};

export default SupportDonateMember;
