// src/components/Home/Hero.jsx
import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import gradient from "../../assets/images/gradient.png";
import Button from "./Button";

const HeroSection = () => {
  const [showFinalScreen, setShowFinalScreen] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setShowFinalScreen(true);
    }, 1500);
  }, []);

  return (
    <div
      id="home"
      className="relative h-screen w-screen flex items-center justify-center overflow-hidden px-6"
      style={{ background: `url(${gradient}) no-repeat center center / cover` }}
    >
      <AnimatePresence mode="wait">
        {!showFinalScreen ? (
          <motion.div
            key="placeholder"
            className="flex flex-col items-center gap-4 text-white"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ x: -1000 }}
            transition={{ duration: 1 }}
          />
        ) : (
          <motion.div
            key="content"
            className="flex flex-col items-center text-center gap-4"
            initial={{ opacity: 0, y: 1000 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -1000 }}
            transition={{ duration: 1 }}
          >
            <h1 className="text-4xl md:text-6xl lg:text-8xl font-extrabold text-[#0464C4]">
              JARURAT CARE
            </h1>
            <h2 className="text-xl md:text-3xl lg:text-4xl font-semibold text-[#132F78]">
              Jaisi Jarurat Vaisi Care
            </h2>
            <p className="text-blue-900 text-sm md:text-lg lg:text-xl max-w-md md:max-w-lg lg:max-w-xl">
              Providing support, guidance, hope, and personalized care for{" "}
              <span className="underline font-bold">cancer patients</span> and
              their families. Here to ensure you never face your journey alone.
            </p>
            <Button text="Seek Cancer Support" />
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default HeroSection;

// src/lib/components/hero.svelte
<script>
  import { fade, fly } from 'svelte/transition';
  import { onMount } from 'svelte';
  import gradient from '../../assets/gradient.png';

  let showFinalScreen = false;

  onMount(() => {
    setTimeout(() => {
      showFinalScreen = true;
    }, 1500);
  });
</script>

<!-- svelte-ignore a11y-no-noninteractive-tabindex -->
<div
  class="relative h-screen w-screen overflow-hidden flex items-center justify-center"
  tabindex="0"
  style="background: url({gradient}) no-repeat center center; background-size: cover;"
>
  {#if !showFinalScreen}
    <div
      class="flex flex-col items-center gap-4 text-white"
      in:fade={{ duration: 500 }}
      out:fly={{ x: -1000, duration: 1000 }}
    >
    </div>
  {/if}

  {#if showFinalScreen}
    <div class="flex flex-col items-center text-center gap-4" in:fly={{ y: 1000, duration: 1000 }}>
      <h1 class="text-8xl font-extrabold" style="color: #0464C4;">JARURAT CARE</h1>
      <h2 class="text-4xl font-semibold" style="color:#132F78">Jaisi Jarurat Vaisi Care</h2>
      <p class="text-blue-900 text-xl max-w-md">
        Providing support, guidance, hope and personalized care for <span
          class="underline font-bold">cancer patients</span
        > and their families. Here to ensure you never face your journey alone.
      </p>
      <button
        class="bg-blue-700 text-white px-6 py-3 rounded-full mt-4 flex items-center relative overflow-hidden transition-all duration-300 ease-in-out hover:bg-blue-300 hover:border-b-4 border-blue-800"
      >
        <span class="text-2xl transition-all duration-300 ease-in-out hover:text-blue-900"
          >Seek Cancer Support</span
        >
      </button>
    </div>
  {/if}
</div>

<style>
  div[tabindex='0'] {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center; 
    gap: 4rem;
    padding: 0;
    margin: 0; 
    cursor: pointer;
    outline: none;
  }
</style>
